init_config:

instances:
  - min_collection_interval: 30 (this will only be utilized if script is being run as a Datadog check(
    subnet: 127.0.0.0 (hope this is obvious on what it should be....)
    tags: ["app:tre","env:local","location:frisco"] (set some tags here) 
