init_config:

instances:
  - min_collection_interval: 30
    subnet: 127.0.0.0 
    tags: ["app:tre","env:local","location:frisco"]  

  - min_collection_interval: 14400
    subnet: 23.202.231.0
    tags: ["app:tre","env:cloud","location:sky"]